### ISSUE TITLE
🐞 SpawnSync doesn't work on windows systems

### ISSUE THREAD

**Issue by leny** [becodeorg/eslint-config#67]
The installation of devDependencies, using [spawnSync](https://github.com/becodeorg/eslint-config/blob/master/src/init.js#L84-L88), doesn't work on Windows systems.

**Comment by leny** [comment]
Had implemented a simple workaround with a warning message.

But [this package](https://www.npmjs.com/package/cross-spawn) should do the job, to be tested.

**Comment by leny** [comment]
Published as `0.7.0`.

@Laodeus > can you test this on your machine? Should install the dependencies correctly now, making useless the idea to gave you a command to write on your own.

**Comment by Laodeus** [comment]
@leny > it worked.

it installed the devDependencies on my home computer.

here are the devdependencies from a package.json in one of my project after i installed the @becode/eslint-config =>

  "devDependencies": {
    "@becode/eslint-config": "^0.7.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^6.3.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-unicorn": "^10.0.0",
    "husky": "^3.0.5",
    "lint-staged": "^9.2.5",
    "parcel": "^1.12.3",
    "prettier": "^1.18.2",
    "sass": "^1.23.0-module.beta.1"
  },

**Comment by leny** [comment]
Nice!

Thanks for testing.
